export { default as Login } from "./login";
export { default as ForgetPass } from "./forget-password";
export { default as Signup } from "./SignUp";
export { default as NotFound } from "./notFound";
export { default as Verify } from "./Verify";
export { default as VerifyPassword } from "./verify-email";
export { default as NewUserLogin } from "./new_userLoginScreen";
export { default as RejectPage } from "./new_userReject";
export { default as ResendPage } from "./resend-email";
