export const routes = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/sign-up",
  FORGET_PASSWORD: "/forgot-password",
  NOT_FOUND: "*",
  PROFILE: "/dashboard/profile",
  DASHBOARD: "/dashboard/activity",
  INDUSTRY: "/dashboard/industry",
  CANDIDATE: "/dashboard/candidate",
  ALL_CANDIDATES: "/dashboard/candidate/all-candidates",
  NEW_REQUEST: "/dashboard/candidate/new-request",
  SINGLE_CANDIDATE: "/dashboard/candidate/single-candidate",
  WORKSPACE: "/dashboard/workspace",
  PRICING: "/dashboard/pricing",
  TEMPLATE_BUILDER: "/dashboard/templates/",
  JOBS: "/dashboard/jobs",
  JOBS_CREATE: "/dashboard/jobs/create",
  HELP_DESK: "/dashboard/help-desk/",
  FORMS: "/dashboard/forms",
  CREATE_NEW_FORM: "/dashboard/create-new-form",
  ALL_FORMS: "/dashboard/all-forms",
  ARCHIVED: "/dashboard/archived",
  DRAFT: "/dashboard/draft",
  SUB_LIST: "/dashboard/submission",
  JOBS_SEARCH: "/jobs/search",
  ALL_FILES: "/dashboard/files/index",
  ARCHIVED_FILES: "/dashboard/files/archived/index",
  SUB_FILE_LIST: "/dashboard/files/submission/index",
  CONTACTS: "/contact-us",
  BLOGS: "/news",
  PRICINGTABLE: "/pricingtable",
  GUEST: "/guest",
  BLOGSPOSTS: "/blogspost",
  JOBSDETAILS: "/jobs/detail",
  RESEND_VERIFICATION: "/resend-verification",
  // --------
  DOCUMENTS: "/dashboard/documents",
  CREATE_NEW_DOCUMENT: "/dashboard/documents/create-new-document",
  ALL_DOCUMENTS: "/dashboard/documents/all-documents",
  ALL_ARCHIVED: "/dashboard/documents/documents-archeived",
  // --------
  FAQS: "/dashboard/help-desk/faqs",
  CONTACT: "/dashboard/help-desk/contact-us",
  INTEGRATIONS: "/dashboard/integration",
  CANDIDATE_DASHBOARD: "/dashboard/candidate",
  CANDIDATE_JOBS: "/dashboard/jobs-candidate",
  CANDIDATE_PROFILE: "/dashboard/profile-candidate",
  CANDIDATE_INTERVIEW: "/dashboard/interview-candidate",
  CANDIDATE_LICENSE: "/dashboard/license-candidate",
  verify_token: "/user/verify",
  verify_email_forget_password: "/user/reset-password",
  REF: "/reference",
  NEW_USER_REQUEST: "/user/request/accept",
  NEW_USER_REJECT: "/user/request/deny",
  COMPANY: "/dashboard/company",
  INTERVIEW: "/dashboard/interview",
  FORM_VIEW: "/dashboard/form/view",
  GUEST_FROM_REQUEST: "/guest/form-request/accept",

  // ORDER_HISTORT
  ORDER_LIST: "/dashboard/pricing/orders/",
  ORDER_DETAIL: "/dashboard/pricing/order",

  //
  SUBSCRIPTION_GET: "/dashboard/pricing/subscription/",
  SUBSCRIPTION_UPDATE: "/dashboard/pricing/subscription-update/",
  SUBSCRIPTION_DELETE: "/dashboard/pricing/subscription-delete",

  // INDUSTRY_CREATE_PAGE: "/dashboard/industry/create-page-1",
  // INDUSTRY_CREATE_PAGE2: "/dashboard/industry/create-page-2",
  // REAL_STATE: "/dashboard/industry/real-state",
  // HOSPITALITY: "/dashboard/industry/hospitality",
  // GIG_ECONMY: "/dashboard/industry/gig-econmy",
  // HEALTH_CARE: "/dashboard/industry/health-care",
  // RECRUITMENT: "/dashboard/industry/recruitment",
  // TRANSPORT: "/dashboard/industry/transport",
  // ENGENERING: "/dashboard/industry/engineering",
  // AGED_CARE: "/dashboard/industry/age-care",

  REQUEST_LIST: "/dashboard/request/list",
  SUBMISSION_LIST: "/dashboard/submit/list",
  GUEST_REFERENCE: "/guest/reference/accept",
};
